server:
  port: 8080

spring:
  application:
    name: trade_system

  datasource:
    url: jdbc:postgresql://localhost:5432/trade_system
    username: trade_user
    password: trade_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ?? ?? ????? update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: always   # Spring Batch ????? ?? ??
    job:
      enabled: false               # ?? ?? ? ?? ?? ?? ?

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
